### ISSUE TITLE
(Feature Request) Auras, Buffs and Debuffs' tooltip showing who casted

### ISSUE THREAD

**Issue by lishpeth** [ElvUI-TBC/ElvUI_Enhanced#12]
If  I remember correctly, there was an extra information in the tooltips of auras (buffs) about being able to see who casted them as in the screenshot below. In raids and parties, this is a great feature to have. Please take it into consideration...

![wowscrnshot_080517_211018](https://user-images.githubusercontent.com/28478416/28997652-893fe9f4-7a22-11e7-8922-e2a5737eaf42.jpg)

Screenshot taken from the Bunny's backported Elvui (wotlk version)

**Comment by Bunny67** [comment]
In TBC can not be implemented
