### ISSUE TITLE
ElvUI and QuestGuru

### ISSUE THREAD

**Issue by Xaner** [ElvUI-TBC/ElvUI_Enhanced#13]
QuestGuru does two things first changes quest tracker this is cool but the second function is it will change quest log and that's a problem. Because when I have just ElvUI without QuestGuru quest log look so cool I love it but when I have at the same time Elvui and QuestGuru quest log starts to look really really weird something between ElvUI and QuestGuru. So I'm asking you if you could somehow synchronize these two different addons.

- Picture of: **ElvUI without QuestGuru**
https://user-images.githubusercontent.com/30808945/29043016-ade71578-7bb9-11e7-9a1e-016ce7fad816.jpg

- Picture of: **ElvUI and QuestGuru**
https://user-images.githubusercontent.com/30808945/29043080-e9592c22-7bb9-11e7-9c08-ba45eb54d187.jpg

**Comment by Loaal** [comment]
Skin added to [ElvUI_AddOnSkins](https://github.com/ElvUI-TBC/ElvUI_AddOnSkins) plugin.
