### ISSUE TITLE
[Feature Request] Energy tick indicator for rogues/cat druids

### ISSUE THREAD

**Issue by ghost** [ElvUI-TBC/ElvUI_Enhanced#16]
A crucial feature for pvp rogues/druids is an energy tick indicator. I like the xperl approach with a thin bar below the energy bar, but anything else would be fine, too.

**Comment by Bunny67** [comment]
Screenshot?

**Comment by ghost** [comment]
It looks like this:
![energy_tick](https://user-images.githubusercontent.com/15674083/29444977-0a527a0a-83e4-11e7-800c-ec1eff34f9cf.png)

**Comment by kevlhw** [comment]
Some addons also have a scrolling light on top of the energy bar as well.

**Comment by Bynzski** [comment]
I also would like to see this enabled.

EnergyWatch has this but would be nice to see implemented in ELVUI
http://www.wowinterface.com/downloads/info6741-EnergyWatch.html

**Comment by Apollyonn** [comment]
I guess something like this will do?

![energyticker](https://user-images.githubusercontent.com/19589902/43643705-e3290c36-9734-11e8-9d0e-868534836031.gif)

**Comment by ghost** [comment]
yep, looks fine

**Comment by dadkinse** [comment]
How do you activate this?

**Comment by comfreak89** [comment]
It stopps when at 100% energy. Is it possible to let it tick further when at 100%?
