### ISSUE TITLE
[Feature Request] Add support to rescale the player and target portrait independantly from HP bar

### ISSUE THREAD

**Issue by minigolfarn** [ElvUI-TBC/ElvUI_Enhanced#19]
In the current version if you add a portrait to the side of the HP bar you cannot move or rescale it separately from the HP bar. I would like to see a feature where you can both move and resize it separately.

**Comment by Apollyonn** [comment]
You can detach the player & target portrait from the hp frames and resize it.
![wowscrnshot_091517_133442](https://user-images.githubusercontent.com/19589902/30478682-b039ba18-9a1a-11e7-9571-24849ef484d1.jpg)
