### ISSUE TITLE
Additional Settings for Combo Points

### ISSUE THREAD

**Issue by Urkaanz** [ElvUI-TBC/ElvUI_Enhanced#22]
Any plans for additional customization options on the look of the combobar on the target unitframe? E.g. the width of the individual combopoints when separated and the color of the bars themselves?

Thanks!

**Comment by Crumdidlyumshis** [comment]
Unfortunately not. We try to keep what original features we can. It is more work than its work to make this type of enhancement. I'm sure there are some addons out there that can provide this type of functionality you're looking for. Hope you find what you're looking for!
