### ISSUE TITLE
Loss Control wrong durations

### ISSUE THREAD

**Issue by Redtuzk** [ElvUI-TBC/ElvUI_Enhanced#3]
Loss Control shows incorrect durations, and it also picks up on stuff that isn't a loss of control (polarity mechanic on Mechanar heroic first boss for example)

![.](http://i.imgur.com/yFXDmVZ.jpg)

**Comment by Apollyonn** [comment]
If the problem appears again, re-open the ticket and report the problematic spell

**Comment by Tremolo4** [comment]
Absurd duration problem occurs for me with Concussion Blow (Warrior, 12809) and Mind Control (Priest), which is 100% of all Spells that I tested :v
