### ISSUE TITLE
Disable AFK mode

### ISSUE THREAD

**Issue by Calthaza** [ElvUI-TBC/ElvUI_Enhanced#33]
Hi there.

Was just wondering if there are any way to disable the AFK mode for 2.4.3 Elv UI

/Calthaza

**Comment by Fanquar** [comment]
You can disable the afk mode by going into ElvUI settings

and under general in the first tab that should open untick "AFK Mode" as shown here
![screenshot_2](https://user-images.githubusercontent.com/41789276/45288378-caa5a380-b4ea-11e8-8c3a-a257be7ed618.jpg)

**Comment by slyt** [comment]
In version 13.89 the "AFK Mode" checkbox is in the General->Cosmetics tab (WoW Classic).

![Image](https://github.com/user-attachments/assets/137ccdea-f4cf-415c-96f9-568cd654bf14)
