### ISSUE TITLE
Nameplates Castbar Duplication

### ISSUE THREAD

**Issue by Fanquar** [ElvUI-TBC/ElvUI_Enhanced#34]
![unknown](https://user-images.githubusercontent.com/41789276/45288479-10fb0280-b4eb-11e8-9f1f-c1c75f30f51d.png)
As seen on this screenshot sometimes the nameplates end up cloning the cast bar onto other mobs.
I believe it only (or usually) happens when the casting mob (in this situation the Haal'eshi Windwalker) is in combat but the duplicated cast bar's target (Kaliri Matriarch) isn't, also it doesn't happen every time and it is rather difficult to reproduce without me knowing exactly what situations cause it

**Comment by Apollyonn** [comment]
try latest commit

**Comment by Fanquar** [comment]
works now as far as I can tell, at least under the same situation in the same mobs
