### ISSUE TITLE
Various Character Pane suggestions

### ISSUE THREAD

**Issue by Redtuzk** [ElvUI-TBC/ElvUI_Enhanced#4]
First of all, thanks a lot for the awesome work you guys do daily, adding suggestions and correcting mistakes super quick.

Here's a couple of things that I've notice with the new (super cool) character pane.

- Since there's an option for durability text being colored by percentage, having one for itemlevel would be awesome too.

I realize this module is super new, and you've probably already worked out some of the stuff I listed internally, but thought I'd post it anyway :)

**Comment by Bunny67** [comment]
- The model window seems to extend a little too far down, clipping into the weapon icons.
![.](http://i.imgur.com/IQS0l6S.png)

- 'Titles'-button is missing it's icon, (could use the one in PaperDollSidebarTabs.blp)
![.](http://i.imgur.com/AgyKHCI.png)

- The "Damage Per Second"-text in the stats overview seems to overlap with certain font/size settings, (could possibly shorten to "DPS" to avoid the issue?)
![.](http://i.imgur.com/ztkgRat.png)

This fixed

**Comment by Bunny67** [comment]
![wowscrnshot_071817_210450](https://user-images.githubusercontent.com/5816685/28332633-2e1f2e90-6bfe-11e7-8abe-4283d19f6261.jpg)

**Comment by Redtuzk** [comment]
@Bunny67 Very nice 👍

**Comment by Crumdidlyumshis** [comment]
👍🏻 very nice! Is this supposed to resemble legion character frame? Buttons?

**Comment by Bunny67** [comment]
- Hate or like it, GearScore seems to be a pretty popular thing on most servers these days. 
Displaying it just above the stats on the right side [like iLvl is on retail](http://i.imgur.com/gGNmUvC.png) instead of [it's default positioning](http://i.imgur.com/RuhXhHw.png) would look great.

Added

**Comment by Bunny67** [comment]
- Font flags for the statpane would be a neat addition.

Unfortunately they will not be added

**Comment by Redtuzk** [comment]
@Bunny67 That's fine, super minor anyway. I'll just add them myself in code. 
That GS change is nuts btw! Great work <3

**Comment by Bunny67** [comment]
- Since there's an option for durability text being colored by percentage, having one for itemlevel would be awesome too.
![wowscrnshot_071817_235808](https://user-images.githubusercontent.com/5816685/28339578-2d9ad32c-6c15-11e7-84f0-c6ced746f1e4.jpg)

**Comment by Redtuzk** [comment]
@Bunny67 I was more thinking something along the lines of how GearScore does it, coloring the text some arbitrary color on a gradient where a deeper color usually means higher ilvl. Mostly up to you to decide how it'd look 👍

**Comment by Bunny67** [comment]
Close? :)

**Comment by Redtuzk** [comment]
@Bunny67 Looks good to me! Thanks for the awesome work
