### ISSUE TITLE
[Feature Request] Nameplate Motion type

### ISSUE THREAD

**Issue by SLouwee** [ElvUI-TBC/ElvUI_Enhanced#51]
Is it possible to have the option to change in the nameplate settings the motion type ?
At the moment, the only and unchangeable setting is "**Stacking Nameplates**", I would like to be able to change it from that to "**Overlapping Nameplates**" like in newer versions of ElvUI

**Comment by Crumdidlyumshis** [comment]
Unfortunately this cannot be done due to nameplates being handled securely. This was added in Wrath. Vanilla has this feature because nameplates are not secure and therefor we were able to do a hacky-method workaround to make it work.
