### ISSUE TITLE
[important] ankh problem

### ISSUE THREAD

**Issue by BastienAuT** [ElvUI-TBC/ElvUI_Enhanced#7]
Hey,

Playing as a shaman since the last update i CANNOT use ankh anymore which is very important for PVE.

once I die i just click on reincarnation yet nothing happens.

**Comment by Bunny67** [comment]
fix in ElvUI
https://github.com/ElvUI-TBC/ElvUI/commit/cdcd817d3b40b53a53ad49bea9d760d72b3f380e
