### ISSUE TITLE
Custom charframe backdrop?

### ISSUE THREAD

**Issue by Redtuzk** [ElvUI-TBC/ElvUI_Enhanced#8]
Is this possible to do? 
Wanted to put a .tga together in photoshop real quick, but unsure of dimensions etc

**Comment by Crumdidlyumshis** [comment]
Yeah you can do so buy looking into the code of PaperDollFrame: https://github.com/goldpaw/WoW_UI_Source_TBC/blob/5be7efce57aa4e4af36494f72ff5788cfcc92c9f/PaperDollFrame.xml#L102

and maybe look into Bunny's code for the Character Frame update in ElvUI_Enahnced: https://github.com/ElvUI-TBC/ElvUI_Enhanced/blob/master/ElvUI_Enhanced/Modules/Misc/characterFrame.lua#L1219

Hope this helps!
